import Script from 'next/script';
import { ThemeProvider } from '@mui/material';
import theme from '@/src/theme/theme';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body>
        <ThemeProvider theme={theme}>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}

export default RootLayout;
